import {useQuery} from '@tanstack/react-query';
import {useTranslation} from 'react-i18next';
import {dashboardApi,bookingsApi} from './api';
import {Loading} from '../../components/ui/Loading';
import {ErrorState} from '../../components/ui/ErrorState';
import {StatusBadge} from '../../components/ui/StatusBadge';
import {BookingChart} from '../../components/ui/BookingChart';
const money=(n:number)=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(n);
export function DashboardPage(){const {t}=useTranslation();const q=useQuery({queryKey:['admin-dashboard'],queryFn:dashboardApi.get});const bookings=useQuery({queryKey:['admin-booking-chart'],queryFn:()=>bookingsApi.list({page:1,limit:200}),staleTime:30_000});if(q.isLoading)return <Loading/>;if(q.isError)return <ErrorState onRetry={()=>q.refetch()}/>;const d=q.data!;return <><div className="page-head"><div><p className="eyebrow">{t('dashboard.eyebrow')}</p><h1>{t('dashboard.greeting',{name:'Admin'})}</h1><p className="muted">{t('dashboard.description')}</p></div><button className="primary">+ {t('dashboard.createBooking')}</button></div><div className="stats"><Stat label={t('dashboard.revenue')} value={money(d.revenue)} delta={d.revenue_change?`${d.revenue_change>0?'+':''}${d.revenue_change}%`:'—'} sub={t('dashboard.vsLastMonth')}/><Stat label={t('dashboard.bookings')} value={String(d.bookings)} delta={d.bookings_change?`${d.bookings_change>0?'+':''}${d.bookings_change}%`:'—'} sub={t('dashboard.thisMonth')}/><Stat label={t('dashboard.occupancy')} value={`${d.occupancy}%`} delta={d.occupancy_change?`${d.occupancy_change>0?'+':''}${d.occupancy_change}%`:'—'} sub={t('dashboard.vsLastMonth')}/><Stat label={t('dashboard.activeRooms')} value={`${d.active_rooms} / ${d.total_rooms}`} delta="" sub={t('dashboard.online')}/></div>
<div className="panel chart-panel"><div className="panel-head"><div><h3>{t('bookingChart.title')}</h3><span>{t('bookingChart.subtitle')}</span></div><span className="chart-note">{bookings.isError?t('bookingChart.unavailable'):t('bookingChart.loaded')}</span></div>{bookings.isLoading?<Loading/>:<BookingChart bookings={bookings.data?.data||[]} days={14}/>}</div>
<div className="grid2"><div className="panel"><div className="panel-head"><div><h3>{t('dashboard.roomOccupancy')}</h3><span>{t('dashboard.todayAll')}</span></div></div><div className="donut"><div><strong>{d.occupancy}%</strong><span>{t('dashboard.occupied')}</span></div></div><div className="legend"><span><i className="dot fill"/>{t('dashboard.occupied')} <b>{d.occupancy}%</b></span><span><i className="dot"/>{t('dashboard.available')} <b>{100-d.occupancy}%</b></span></div></div><div className="panel"><div className="panel-head"><div><h3>{t('dashboard.recent')}</h3><span>{t('dashboard.latestActivity')}</span></div></div><div className="table-wrap"><table><thead><tr><th>{t('table.booking')}</th><th>{t('table.guest')}</th><th>{t('table.time')}</th><th>{t('common.status')}</th><th>{t('table.total')}</th></tr></thead><tbody>{d.recent_bookings.map(b=><tr key={b.id}><td>{b.booking_code}</td><td>{b.guest_name||'—'}</td><td>{new Date(b.start_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})} – {new Date(b.end_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</td><td><StatusBadge status={b.status}/></td><td>{money(b.total)}</td></tr>)}</tbody></table></div></div></div></>}
function Stat({label,value,delta,sub}:{label:string;value:string;delta:string;sub:string}){return <div className="stat"><span>{label}</span><strong>{value}</strong><div><em>{delta}</em><small>{sub}</small></div></div>}
